
language: node_js
node_js:
  - 8
  - 10
  - 12
before_install:
  - git remote set-branches --add origin master && git fetch
after_install:
  env:
  - NODE_ENV=production
jobs:
  include:
    - stage: deploy
      node_js:
        - 10
      deploy:
        provider: npm
        skip_cleanup: true
        edge: true
        on:
          tags: true
          repo: americanexpress/parrot
